spring.application.name=LPM_v3
spring.datasource.url=jdbc:postgresql://localhost:5432/lpm_db
spring.datasource.username=postgres
spring.datasource.password=şifrenizi girin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
upload.static.path=src/main/resources/static/images/
# Tarayıcıdan erişirken kullanılacak URL ön eki
upload.display.path=/images/
